CREATE TABLE `user` (
  id INT AUTO_INCREMENT NOT NULL,
  username VARCHAR(64) NOT NULL,
  password CHAR(64) CHARACTER SET ascii NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (username)
) ENGINE='InnoDB' DEFAULT CHARSET='utf8mb4';

CREATE TABLE `album` (
  id INT AUTO_INCREMENT NOT NULL,
  owner_id INT NOT NULL,
  title VARCHAR(256) NOT NULL,
  alias VARCHAR(64) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (alias)
) ENGINE='InnoDB' DEFAULT CHARSET='utf8mb4';

CREATE TABLE `photo` (
  id INT AUTO_INCREMENT NOT NULL,
  album_id INT NOT NULL,
  title VARCHAR(64) NULL,
  text TEXT NULL,
  preview_url VARCHAR(2048) NULL,
  raw_url VARCHAR(2048) NOT NULL,
  photo_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX (album_id)
) ENGINE='InnoDB' DEFAULT CHARSET='utf8mb4';

CREATE TABLE `config` (
  `key` VARCHAR(256) NOT NULL,
  `value` VARCHAR(4096) NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE='InnoDB' DEFAULT CHARSET='utf8mb4';
